version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=studyapp
      - POSTGRES_PASSWORD=studyapp123
      - POSTGRES_DB=notes  # This specifies the database to create
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U studyapp -d notes"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - OLLAMA_API_URL=http://abts55669.de.bosch.com:11434
      - OLLAMA_MODEL=phi4:14b
      - DATABASE_URL=postgresql://studyapp:studyapp123@db:5432/notes
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  postgres_data: